language: rust
cache: cargo
os:
    - linux
    - osx
    - windows
rust:
    - stable
    - beta
    - nightly
    - 1.29.2
    - 1.29.1
    - 1.29.0
    - 1.28.0
    - 1.27.2
    - 1.27.1
    - 1.27.0
script:
    - cargo test --verbose --all
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
        - os: osx