language: rust

cache: cargo

os:
    - linux
    - osx

rust:
    - stable
    - beta
    - nightly
    

script:
    - cargo test --verbose --all

matrix:
    allow_failures:
        - rust: nightly