/// Enumeration of available API endpoints from the Guild Wars 2 API.
/// Used internally to  aid in the consistent generation of URLs as part of fetching API data.
#[derive(Debug)]
pub(crate) enum Endpoint {
    Achievements,
    AchievementsCategories,
    AchievementsDaily,
    AchievementsDailyTomorrow,
    AchievementsGroups,
    BackstoryAnswers,
    BackstoryQuestions,
    Build,
    Cats,
    Colors,
    Currencies,
    CommerceDelivery,
    CommerceExchangeCoins,
    CommerceExchangeGems,
    CommerceListings,
    CommercePrices,
    CommerceTransactionsCurrentBuys,
    CommerceTransactionsCurrentSells,
    CommerceTransactionsHistoryBuys,
    CommerceTransactionsHistorySells,
    Gliders,
    Legends,
    Specializations,
    Stories,
    StorySeasons,
    Titles,
    TokenInfo,
    Worlds,
    WVWAbilities,
    WVWMatches,
    WVWObjectives,
    WVWRanks,
    WVWUpgrades,
}

impl Endpoint {
    pub fn as_str(&self) -> &str {
        match *self {
            Endpoint::Achievements => "/achievements",
            Endpoint::AchievementsCategories => "/achievements/categories",
            Endpoint::AchievementsDaily => "/achievements/daily",
            Endpoint::AchievementsDailyTomorrow => "/achievements/daily/tomorrow",
            Endpoint::AchievementsGroups => "/achievements/groups",
            Endpoint::BackstoryAnswers => "/backstory/answers",
            Endpoint::BackstoryQuestions => "/backstory/questions",
            Endpoint::Build => "/build",
            Endpoint::Cats => "/cats",
            Endpoint::Colors => "/colors",
            Endpoint::Currencies => "/currencies",
            Endpoint::CommerceDelivery => "/commerce/delivery",
            Endpoint::CommerceExchangeCoins => "/commerce/exchange/coins",
            Endpoint::CommerceExchangeGems => "/commerce/exchange/gems",
            Endpoint::CommerceListings => "/commerce/listings",
            Endpoint::CommercePrices => "/commerce/prices",
            Endpoint::CommerceTransactionsCurrentBuys => "/commerce/transactions/current/buys",
            Endpoint::CommerceTransactionsCurrentSells => "/commerce/transactions/current/sells",
            Endpoint::CommerceTransactionsHistoryBuys => "/commerce/transactions/history/buys",
            Endpoint::CommerceTransactionsHistorySells => "/commerce/transactions/history/sells",
            Endpoint::Gliders => "/gliders",
            Endpoint::Legends => "/legends",
            Endpoint::Specializations => "/specializations",
            Endpoint::Stories => "/stories",
            Endpoint::StorySeasons => "/stories/seasons",
            Endpoint::Titles => "/titles",
            Endpoint::TokenInfo => "/tokeninfo",
            Endpoint::Worlds => "/worlds",
            Endpoint::WVWAbilities => "/wvw/abilities",
            Endpoint::WVWMatches => "/wvw/matches",
            Endpoint::WVWObjectives => "/wvw/objectives",
            Endpoint::WVWRanks => "/wvw/ranks",
            Endpoint::WVWUpgrades => "/wvw/upgrades",
        }
    }
}
